Vagrant.configure("2") do |config|
	config.vm.box = "bento/ubuntu-18.10"
	config.vm.provider "virtualbox" do |v|
		v.memory = 6144 # 6GB
		v.cpus = 4
	end
	config.vm.provision "shell", path: "vagrant-script.sh"
end